some simplifications
crytic/echidna pull request #513
Opened 2020-09-11 15:55 UTC by incertia

let us use this branch and PR to perform tasks related to #487

2020-11-16 18:10 UTC, ggrieco-tob requested changes

2020-11-16 18:14 UTC, ggrieco-tob commented on lib/Echidna/Campaign.hs
> +  let l = hasLens . coverage
Can we get a better name for this, instead of `l` ?

2020-11-16 18:15 UTC, ggrieco-tob commented on lib/Echidna/Campaign.hs
> +randseq :: ( MonadRandom m, MonadReader x m, MonadState y m
What is the benefit here?

2020-11-16 19:57 UTC, incertia commented on lib/Echidna/Campaign.hs
> +        rec   = updateGasInfo ts tseq' (insert f (used', reverse tseq') gi)
not reserved just github

2020-11-16 19:57 UTC, incertia commented on lib/Echidna/Campaign.hs
> +  l %= mapWithKey (\_ s -> DS.map (set _2 vmr) s)
with lens this change is easy to make

2020-11-16 19:58 UTC, incertia commented on lib/Echidna/Campaign.hs
> +randseq :: ( MonadRandom m, MonadReader x m, MonadState y m
no explicit `runReaderT` in `callseq`

2020-11-16 20:09 UTC, incertia commented on lib/Echidna/Campaign.hs
> +isSuccess (toListOf (tests . traverse . _2) -> ts) =
check the new version

2020-11-19 19:31 UTC, ggrieco-tob approved these changes

2020-11-19 20:07 UTC, merged