Fixed the use of large constants in the dictionary
crytic/echidna pull request #523
Opened 2020-10-21 12:52 UTC by ggrieco-tob

2020-10-23 19:56 UTC, incertia requested changes

2020-10-23 19:56 UTC, incertia commented on lib/Echidna/Solidity.hs
> +largeConstants = concatMap (\i -> [mkLargeAbiInt i, mkLargeAbiUInt i]) [8,16..256]
let's pull out `[8, 16, ...]` into a variable

2020-10-23 19:56 UTC, incertia commented on lib/Echidna/Solidity.hs
> +mkLargeAbiUInt i = AbiUInt i $ (2 ^ i) - 1
we don't need parens here

2020-10-30 19:20 UTC, ggrieco-tob commented on lib/Echidna/Solidity.hs
> +mkLargeAbiUInt i = AbiUInt i $ (2 ^ i) - 1
It's odd that hlint won't warn about it

2020-10-30 19:33 UTC, ggrieco-tob commented on lib/Echidna/Solidity.hs
> +largeConstants = concatMap (\i -> [mkLargeAbiInt i, mkLargeAbiUInt i]) [8,16..256]
Fixed.

2020-10-30 19:33 UTC, ggrieco-tob commented on lib/Echidna/Solidity.hs
> +mkLargeAbiUInt i = AbiUInt i $ (2 ^ i) - 1
Fixed.

2020-10-30 19:41 UTC, incertia approved these changes

2020-10-30 21:44 UTC, merged