Coverage types refactor and added corpus size in UI
crytic/echidna pull request #627
Opened 2021-03-06 12:02 UTC by ggrieco-tob

2021-03-08 23:06 UTC, incertia requested changes

2021-03-08 23:06 UTC, incertia commented on lib/Echidna/Types/Corpus.hs
>  type Corpus = Set (Integer, [Tx])
consider `newtype`-ing this if you want type-specific size/whatever

2021-03-08 23:06 UTC, incertia commented on lib/Echidna/Types/Coverage.hs
> +
extra newlines

2021-03-08 23:06 UTC, incertia commented on lib/Echidna/Types/Corpus.hs
> +import Data.Set (Set, size)
`length` is defaulted to `size`

https://hackage.haskell.org/package/containers-0.6.4.1/docs/src/Data.Set.Internal.html#line-317

semantics up to you

2021-03-14 21:52 UTC, neuromancer commented on lib/Echidna/Types/Coverage.hs
> +scoveragePoints = sum . fmap (size . Data.Set.map fst3)
Done

2021-03-14 21:53 UTC, ggrieco-tob commented on lib/Echidna/Types/Coverage.hs
> +scoveragePoints = sum . fmap (size . Data.Set.map fst3)
Done.

2021-03-14 21:55 UTC, ggrieco-tob commented on lib/Echidna/Types/Coverage.hs
> +
Done

2021-03-15 19:18 UTC, merged